### ISSUE TITLE
How to run the executable

### ISSUE THREAD

**Issue by yabbasi31415** [remram44/java-cpp-example#4]
Hi, I have successfully compiled the project through cmake and make (without making any changes to the code). I can't figure out where the executable is being generated and how do I run the executable? 

From some other JNI tutorials, I learned this
`java -Djava.library.path=. <executable-name>`
But I get the class not found error in this case

Thanks!

**Comment by remram44** [comment]
You can find the commands in the "testing" section at the bottom of each CMakeLists.txt file. [For example, for JNI](https://github.com/remram44/java-cpp-example/blob/695b3b9c5b1081d0e9df9a7f9197f110e30fe5c9/java-jni/CMakeLists.txt#L68-L71):

```
java -cp java-jni/java/bin -Djava.library.path=java-jni edu.nyu.cpptest.app.Main
```

**Comment by yabbasi31415** [comment]
Thank you, it works!
